import { handlePing } from './ping.js';
import { handleLurk } from './lurk.js';
import { handleRoast } from './roast.js';
import { handleClip, handleHighlights } from './clips.js';
import {
  handleTitle,
  handleCategory,
  handleUptime,
  handleMilestone,
  handleChatInsights,
} from './streamInsights.js';
import {
  handleSuspiciousFollowers,
  handleClearSuspicious,
  handleFollowSettings,
  handleFollowStats,
  handleFollowCheck,
  handleFollowMode,
} from './followProtection.js';
import {
  handleRecommendations,
  handleViewerStats,
  handleLoyalty,
  handleTopViewers,
  handleRaids,
  handleHealth,
  handleBestTimes,
  handleTopCategories,
} from './analytics.js';
import {
  handleCreateClip,
  handleClipsByCategory,
  handleClipsByTag,
  handleRecentClips,
  handleTopClips,
  handleClipStats,
  handleSuggestCompilation,
  handleAnalyzeClip,
} from './clipManagement.js';
import { handleShoutout } from './shoutout.js';
import { startTrivia, handleTriviaAnswer, endTrivia, listCategories } from './trivia.js';
import { competitorCommands } from './competitor.js';
import {
  handleSongRequest,
  handleListQueue,
  handleClearQueue,
  handleRemoveFromQueue,
} from './queue.js';
import {
  handleAddCommand,
  handleRemoveCommand,
  handleListCommands,
  handleUserCommands,
  handleModCommands,
} from './customCommands.js';
import { handleStartWordChain, handleStartMiniGame, handleAnswer } from './games.js';
import { viewerCommands } from './viewer.js';
import { analyticsCommands } from './analyticsCommands.js';
import { handleHug } from './hug.js';
import {
  handleChatActivity,
  handleStreamHealth,
  handleStreamStats,
  handleStreamPerformance,
} from './streamHandlers.js';
import {
  handleMood,
  handleEngagement,
  handleChatStats,
  handlePoints,
  handleLastActive,
  handleStreamSummary,
  handleContentInsights,
  handleStreamPerformance as handleEnhancedPerformance,
  enhancedCommandList,
  enhancedCommands,
} from './enhancedCommands.js';
import { handleSlap } from './slap.js';
import { FMKCommand } from '../../commands/fmk.js';
import unifiedModerationManager from '../unifiedModerationManager.js';
import welcomeManager from '../welcomeManager.js';

// Define moderation commands
const moderationCommands = {
  handleModStats: (...args) => unifiedModerationManager.handleModStats(...args),
  handleUserHistory: (...args) => unifiedModerationManager.handleUserHistory(...args),
  handleTrust: (...args) => unifiedModerationManager.trustUser(...args),
  handleUntrust: (...args) => unifiedModerationManager.untrustUser(...args),
  handleTrusted: (...args) => unifiedModerationManager.handleTrusted(...args),
  handleRaidHistory: (...args) => unifiedModerationManager.handleRaidHistory(...args),
  handleAnalyzeChat: (...args) => unifiedModerationManager.handleAnalyzeChat(...args),
  handleWarn: (...args) => unifiedModerationManager.handleWarn(...args),
  moderateMessage: (...args) => unifiedModerationManager.moderateMessage(...args),
};

// Destructure moderation commands for individual exports
const {
  handleModStats,
  handleUserHistory,
  handleTrust,
  handleUntrust,
  handleTrusted,
  handleRaidHistory,
  handleAnalyzeChat,
  handleWarn,
  moderateMessage,
} = moderationCommands;

// Export all commands
export {
  handlePing,
  handleLurk,
  handleRoast,
  handleChatActivity,
  handleClip,
  handleHighlights,
  handleTitle,
  handleCategory,
  handleUptime,
  handleMilestone,
  handleChatInsights,
  handleSuspiciousFollowers,
  handleClearSuspicious,
  handleFollowSettings,
  handleFollowStats,
  handleFollowCheck,
  handleFollowMode,
  handleRecommendations,
  handleViewerStats,
  handleLoyalty,
  handleTopViewers,
  handleRaids,
  handleHealth,
  handleBestTimes,
  handleTopCategories,
  handleCreateClip,
  handleClipsByCategory,
  handleClipsByTag,
  handleRecentClips,
  handleTopClips,
  handleClipStats,
  handleSuggestCompilation,
  handleAnalyzeClip,
  competitorCommands,
  handleShoutout,
  startTrivia,
  handleTriviaAnswer,
  endTrivia,
  listCategories,
  handleSongRequest,
  handleListQueue,
  handleClearQueue,
  handleRemoveFromQueue,
  handleAddCommand,
  handleRemoveCommand,
  handleListCommands,
  handleUserCommands,
  handleModCommands,
  handleStartWordChain,
  handleStartMiniGame,
  handleAnswer,
  viewerCommands,
  analyticsCommands,
  handleHug,
  handleStreamHealth,
  handleStreamStats,
  handleStreamPerformance,
  // New enhanced commands
  handleMood,
  handleEngagement,
  handleChatStats,
  handlePoints,
  handleLastActive,
  handleStreamSummary,
  handleContentInsights,
  handleEnhancedPerformance,
  enhancedCommands,
  handleSlap,
  FMKCommand,
  welcomeManager,
  // Add moderation exports
  handleModStats,
  handleUserHistory,
  handleTrust,
  handleUntrust,
  handleTrusted,
  handleRaidHistory,
  handleAnalyzeChat,
  handleWarn,
  moderateMessage,
  moderationCommands,
};

// List of available commands for !help
export const commandList = [
  '!ping - Check if bot is online',
  "!lurk - Let chat know you're lurking in a funny way",
  '!roast [@user] - Get a friendly roast',
  '!clip [title] - Create a clip',
  '!highlights [days] - Show recent highlights',
  '!title [new title] - Change stream title (mods only)',
  '!category [game] - Change stream category (mods only)',
  '!uptime - Show stream uptime',
  '!milestone [description] - Add stream milestone (mods only)',
  '!suspicious - Show suspicious followers (broadcaster only)',
  '!clearsuspicious - Clear suspicious followers list (broadcaster only)',
  '!followsettings - Configure follow protection (broadcaster only)',
  '!recommendations - Get stream recommendations',
  '!chatinsights - Show chat analytics',
  '!viewerstats - Show viewer statistics',
  '!loyalty - Show loyalty program stats',
  '!topviewers - Show top chatters',
  '!raids - Show recent raids',
  '!health - Show stream health',
  '!performance - Show stream performance',
  '!besttimes - Show best streaming times',
  '!topcategories - Show top performing categories',
  '!createclip [title] - Create a new clip',
  '!clipsbycategory [category] - Show clips by category',
  '!clipsbytag [tag] - Show clips by tag',
  '!recentclips [days] - Show recent clips',
  '!topclips - Show most viewed clips',
  '!clipstats - Show clip statistics',
  '!suggestcompilation - Get clip compilation suggestions',
  '!analyzeclip [clipId] - Analyze a specific clip',
  '!modstats - Show moderation statistics (mods only)',
  '!userhistory [username] - Show user history (mods only)',
  '!trust [username] - Add user to trusted list (mods only)',
  '!untrust [username] - Remove user from trusted list (mods only)',
  '!raidhistory - Show raid history (mods only)',
  '!analyzechat - Show chat analysis (mods only)',
  '!warn [username] [reason] - Warn a user (mods only)',
  '!track [channel] - Track competitor channel (broadcaster only)',
  '!untrack [channel] - Stop tracking channel (broadcaster only)',
  '!insights - Show competitor insights (broadcaster only)',
  '!suggestions - Get content suggestions (broadcaster only)',
  '!tracked - List tracked channels (broadcaster only)',
  '!shoutout [@user] - Give someone a shoutout (mods only)',
  '!trivia [category] - Start a trivia game (mods only)',
  '!categories - List available trivia categories',
  '!answer [A/B/C/D] - Submit your answer for the current trivia question',
  '!endtrivia - End current trivia game and show final scores (mods only)',
  '!songrequest [song name] - Request a song to be played',
  '!queue - Show current song queue',
  '!clearqueue - Clear the song queue (mods only)',
  '!queueremove [position] - Remove a song from the queue',
  '!addcom [command] [response] - Add a custom command (mods only)',
  '!delcom [command] - Remove a custom command (mods only)',
  '!commands - List all available commands',
  '!listcommands - List all custom commands',
  '!mods (or !mod) - List all moderator commands (mods only)',
  '!wordchain - Start a word chain game (mods only)',
  '!minigame [scramble|riddle] - Start a mini game (mods only)',
  '!stats - Show viewer statistics',
  '!loyalty - Show loyalty distribution',
  '!topviewers - Show top viewers',
  '!raids - Show recent raids',
  '!peak - Show peak viewers',
  '!growth - Show growth stats',
  '!trending - Show trending segments',
  '!recap - Generate stream recap',
  '!vibe - Get chat vibe',
  '!schedule - Get schedule recommendations',
  '!tags - Get tag recommendations',
  '!collab - Find collaboration partners (broadcaster only)',
  '!network - Get networking effectiveness',
  '!followstats - Show follow statistics',
  '!followcheck [username] - Check specific follower',
  '!followmode [on/off] - Configure follow mode (mods only)',
  '!streamstats - Show stream statistics',
  '!streamhealth - Show stream health',
  '!hug [@user] - Send a warm AI-generated hug to someone',
  '!slap [@user] - Slap someone with random power! (1-100%)',
  '!fmk - Play a game of FMK with random chatters',
  // Add new enhanced commands
  ...enhancedCommandList,
  '!trusted - Show list of trusted users (mods only)',
];
