import {
  handlePing,
  handleLurk,
  handleRoast,
  handleChatActivity,
  handleClip,
  handleHighlights,
  handleTitle,
  handleCategory,
  handleUptime,
  handleMilestone,
  handleChatInsights,
  handleSuspiciousFollowers,
  handleClearSuspicious,
  handleFollowSettings,
  handleFollowStats,
  handleFollowCheck,
  handleFollowMode,
  handleRecommendations,
  handleViewerStats,
  handleLoyalty,
  handleTopViewers,
  handleRaids,
  handleHealth,
  handleBestTimes,
  handleTopCategories,
  handleCreateClip,
  handleClipsByCategory,
  handleClipsByTag,
  handleRecentClips,
  handleTopClips,
  handleClipStats,
  handleSuggestCompilation,
  handleAnalyzeClip,
  handleModStats,
  handleUserHistory,
  handleTrust,
  handleUntrust,
  handleRaidHistory,
  handleAnalyzeChat,
  handleWarn,
  moderateMessage,
  advancedModeration,
  competitorCommands,
  handleShoutout,
  startTrivia,
  handleTriviaAnswer,
  endTrivia,
  listCategories,
  handleSongRequest,
  handleListQueue,
  handleClearQueue,
  handleRemoveFromQueue,
  handleAddCommand,
  handleRemoveCommand,
  handleListCommands,
  handleUserCommands,
  handleModCommands,
  handleStartWordChain,
  handleStartMiniGame,
  handleAnswer,
  viewerCommands,
  analyticsCommands,
  handleStreamHealth,
  handleStreamStats,
  handleStreamPerformance,
  handleMood,
  handleEngagement,
  handleChatStats,
  handlePoints,
  handleLastActive,
  handleStreamSummary,
  handleContentInsights,
  handleEnhancedPerformance,
  enhancedCommands,
} from '../../bot/commands/index.js';

const mockClient = {
  say: jest.fn(),
  mods: jest.fn(),
  vips: jest.fn(),
  getMods: jest.fn().mockResolvedValue(['mod1', 'mod2']),
  getVips: jest.fn().mockResolvedValue(['vip1', 'vip2']),
  ban: jest.fn(),
  timeout: jest.fn(),
  whisper: jest.fn(),
  action: jest.fn(),
  chat: jest.fn(),
  join: jest.fn(),
  part: jest.fn(),
  ping: jest.fn(),
  pong: jest.fn(),
  connect: jest.fn(),
  disconnect: jest.fn(),
  getChannelInfo: jest.fn(),
  getStreamInfo: jest.fn(),
  getClipInfo: jest.fn(),
  getChatters: jest.fn(),
  getFollowers: jest.fn(),
  getSubscribers: jest.fn(),
  getCheermotes: jest.fn(),
  getEmotes: jest.fn(),
  getBadges: jest.fn(),
  getTags: jest.fn(),
  getGames: jest.fn(),
  getUsers: jest.fn(),
  getStreams: jest.fn(),
  getClips: jest.fn(),
  getVideos: jest.fn(),
  getChatSettings: jest.fn(),
  updateChatSettings: jest.fn(),
  sendMessage: jest.fn(),
  deleteMessage: jest.fn(),
  clearChat: jest.fn(),
  timeoutUser: jest.fn(),
  banUser: jest.fn(),
  unbanUser: jest.fn(),
  getChannelEditors: jest.fn(),
  getChannelTeams: jest.fn(),
  getChannelSubscriptions: jest.fn(),
  getChannelBitsLeaderboard: jest.fn(),
  getChannelExtensions: jest.fn(),
  getChannelExtension: jest.fn(),
  getChannelVips: jest.fn(),
  getChannelModerators: jest.fn(),
  getChannelFollowers: jest.fn(),
  getChannelSubscribers: jest.fn(),
  getChannelCheermotes: jest.fn(),
  getChannelEmotes: jest.fn(),
  getChannelBadges: jest.fn(),
  getChannelTags: jest.fn(),
  getChannelGames: jest.fn(),
  getChannelUsers: jest.fn(),
  getChannelStreams: jest.fn(),
  getChannelClips: jest.fn(),
  getChannelVideos: jest.fn(),
  getChannelChatSettings: jest.fn(),
  updateChannelChatSettings: jest.fn(),
  sendChannelMessage: jest.fn(),
  deleteChannelMessage: jest.fn(),
  clearChannelChat: jest.fn(),
  timeoutChannelUser: jest.fn(),
  banChannelUser: jest.fn(),
  unbanChannelUser: jest.fn(),
  getChannelEditor: jest.fn(),
  getChannelTeam: jest.fn(),
  getChannelSubscription: jest.fn(),
  getChannelVip: jest.fn(),
  getChannelModerator: jest.fn(),
  getChannelFollower: jest.fn(),
  getChannelSubscriber: jest.fn(),
  getChannelCheermote: jest.fn(),
  getChannelEmote: jest.fn(),
  getChannelBadge: jest.fn(),
  getChannelTag: jest.fn(),
  getChannelGame: jest.fn(),
  getChannelUser: jest.fn(),
  getChannelStream: jest.fn(),
  getChannelClip: jest.fn(),
  getChannelVideo: jest.fn(),
  getChannelChatSetting: jest.fn(),
  updateChannelChatSetting: jest.fn(),
};

import { jest } from '@jest/globals';

// Mock Twitch client and database
const mockClient = {
  say: jest.fn(),
  mods: jest.fn(),
  vips: jest.fn(),
  getMods: jest.fn().mockResolvedValue(['mod1', 'mod2']),
  getVips: jest.fn().mockResolvedValue(['vip1', 'vip2']),
  ban: jest.fn(),
  timeout: jest.fn(),
  whisper: jest.fn(),
  action: jest.fn(),
  chat: jest.fn(),
  join: jest.fn(),
  part: jest.fn(),
  ping: jest.fn(),
  pong: jest.fn(),
  connect: jest.fn(),
  disconnect: jest.fn(),
  getChannelInfo: jest.fn(),
  getStreamInfo: jest.fn(),
  getClipInfo: jest.fn(),
  getChatters: jest.fn(),
  getFollowers: jest.fn(),
  getSubscribers: jest.fn(),
  getCheermotes: jest.fn(),
  getEmotes: jest.fn(),
  getBadges: jest.fn(),
  getTags: jest.fn(),
  getGames: jest.fn(),
  getUsers: jest.fn(),
  getStreams: jest.fn(),
  getClips: jest.fn(),
  getVideos: jest.fn(),
  getChatSettings: jest.fn(),
  updateChatSettings: jest.fn(),
  sendMessage: jest.fn(),
  deleteMessage: jest.fn(),
  clearChat: jest.fn(),
  timeoutUser: jest.fn(),
  banUser: jest.fn(),
  unbanUser: jest.fn(),
  getChannelEditors: jest.fn(),
  getChannelTeams: jest.fn(),
  getChannelSubscriptions: jest.fn(),
  getChannelBitsLeaderboard: jest.fn(),
  getChannelExtensions: jest.fn(),
  getChannelExtension: jest.fn(),
  getChannelVips: jest.fn(),
  getChannelModerators: jest.fn(),
  getChannelFollowers: jest.fn(),
  getChannelSubscribers: jest.fn(),
  getChannelCheermotes: jest.fn(),
  getChannelEmotes: jest.fn(),
  getChannelBadges: jest.fn(),
  getChannelTags: jest.fn(),
  getChannelGames: jest.fn(),
  getChannelUsers: jest.fn(),
  getChannelStreams: jest.fn(),
  getChannelClips: jest.fn(),
  getChannelVideos: jest.fn(),
  getChannelChatSettings: jest.fn(),
  updateChannelChatSettings: jest.fn(),
  sendChannelMessage: jest.fn(),
  deleteChannelMessage: jest.fn(),
  clearChannelChat: jest.fn(),
  timeoutChannelUser: jest.fn(),
  banChannelUser: jest.fn(),
  unbanChannelUser: jest.fn(),
  getChannelEditor: jest.fn(),
  getChannelTeam: jest.fn(),
  getChannelSubscription: jest.fn(),
  getChannelVip: jest.fn(),
  getChannelModerator: jest.fn(),
  getChannelFollower: jest.fn(),
  getChannelSubscriber: jest.fn(),
  getChannelCheermote: jest.fn(),
  getChannelEmote: jest.fn(),
  getChannelBadge: jest.fn(),
  getChannelTag: jest.fn(),
  getChannelGame: jest.fn(),
  getChannelUser: jest.fn(),
  getChannelStream: jest.fn(),
  getChannelClip: jest.fn(),
  getChannelVideo: jest.fn(),
  getChannelChatSetting: jest.fn(),
  updateChannelChatSetting: jest.fn(),
};
